[package]
name = "jazztastic"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre.workspace = true
hex-literal.workspace = true
serde.workspace = true
thiserror.workspace = true
log.workspace = true
chrono.workspace = true

bitflags = "2.10.0"
hidapi = "2.6.4"
pcap-parser = "0.17.0"
strum = { version = "0.27.2", features = ["derive"] }
