[package]
name = "openajazz"
version = "0.1.0"
edition = "2024"

[dependencies]
jazztastic = { path = "../jazztastic" }
color-eyre = "0.6.5"
env_logger = "0.11.8"
log = "0.4.29"
notify = "8.2.0"
notify-debouncer-full = "0.7.0"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
toml = "0.9.11"
